apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-prd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/CasperGN/intro-argo-cd-tutorial'
    path: guestbook
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-prd.yaml
  destination:
    namespace: guestbook-prd
    name: scni-eks-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
